2024-04-17 01:01:23 | INFO | model_worker | Loading the model ['chatglm3-6b'] on worker 094af387 ...
2024-04-17 01:01:24 | ERROR | stderr | Loading checkpoint shards:   0%|                                                                 | 0/7 [00:00<?, ?it/s]
2024-04-17 01:01:24 | ERROR | stderr | Loading checkpoint shards:  14%|████████▏                                                | 1/7 [00:00<00:02,  2.68it/s]
2024-04-17 01:01:24 | ERROR | stderr | Loading checkpoint shards:  29%|████████████████▎                                        | 2/7 [00:00<00:01,  2.62it/s]
2024-04-17 01:01:25 | ERROR | stderr | Loading checkpoint shards:  43%|████████████████████████▍                                | 3/7 [00:01<00:01,  2.63it/s]
2024-04-17 01:01:25 | ERROR | stderr | Loading checkpoint shards:  57%|████████████████████████████████▌                        | 4/7 [00:01<00:01,  2.71it/s]
2024-04-17 01:01:25 | ERROR | stderr | Loading checkpoint shards:  71%|████████████████████████████████████████▋                | 5/7 [00:01<00:00,  2.70it/s]
2024-04-17 01:01:26 | ERROR | stderr | Loading checkpoint shards:  86%|████████████████████████████████████████████████▊        | 6/7 [00:02<00:00,  2.68it/s]
2024-04-17 01:01:26 | ERROR | stderr | Loading checkpoint shards: 100%|█████████████████████████████████████████████████████████| 7/7 [00:02<00:00,  3.02it/s]
2024-04-17 01:01:26 | ERROR | stderr | Loading checkpoint shards: 100%|█████████████████████████████████████████████████████████| 7/7 [00:02<00:00,  2.81it/s]
2024-04-17 01:01:26 | ERROR | stderr | 
2024-04-17 01:01:26 | ERROR | stderr | Process model_worker - chatglm3-6b:
2024-04-17 01:01:26 | ERROR | stderr | Traceback (most recent call last):
2024-04-17 01:01:26 | ERROR | stderr |   File "D:\Program_files\anaconda\envs\chatchat1\lib\multiprocessing\process.py", line 314, in _bootstrap
2024-04-17 01:01:26 | ERROR | stderr |     self.run()
2024-04-17 01:01:26 | ERROR | stderr |   File "D:\Program_files\anaconda\envs\chatchat1\lib\multiprocessing\process.py", line 108, in run
2024-04-17 01:01:26 | ERROR | stderr |     self._target(*self._args, **self._kwargs)
2024-04-17 01:01:26 | ERROR | stderr |   File "C:\Users\li\Langchain-Chatchat\startup.py", line 389, in run_model_worker
2024-04-17 01:01:26 | ERROR | stderr |     app = create_model_worker_app(log_level=log_level, **kwargs)
2024-04-17 01:01:26 | ERROR | stderr |   File "C:\Users\li\Langchain-Chatchat\startup.py", line 217, in create_model_worker_app
2024-04-17 01:01:26 | ERROR | stderr |     worker = ModelWorker(
2024-04-17 01:01:26 | ERROR | stderr |   File "D:\Program_files\anaconda\envs\chatchat1\lib\site-packages\fastchat\serve\model_worker.py", line 77, in __init__
2024-04-17 01:01:26 | ERROR | stderr |     self.model, self.tokenizer = load_model(
2024-04-17 01:01:26 | ERROR | stderr |   File "D:\Program_files\anaconda\envs\chatchat1\lib\site-packages\fastchat\model\model_adapter.py", line 362, in load_model
2024-04-17 01:01:26 | ERROR | stderr |     model.to(device)
2024-04-17 01:01:26 | ERROR | stderr |   File "D:\Program_files\anaconda\envs\chatchat1\lib\site-packages\transformers\modeling_utils.py", line 2595, in to
2024-04-17 01:01:26 | ERROR | stderr |     return super().to(*args, **kwargs)
2024-04-17 01:01:26 | ERROR | stderr |   File "D:\Program_files\anaconda\envs\chatchat1\lib\site-packages\torch\nn\modules\module.py", line 1160, in to
2024-04-17 01:01:26 | ERROR | stderr |     return self._apply(convert)
2024-04-17 01:01:26 | ERROR | stderr |   File "D:\Program_files\anaconda\envs\chatchat1\lib\site-packages\torch\nn\modules\module.py", line 810, in _apply
2024-04-17 01:01:26 | ERROR | stderr |     module._apply(fn)
2024-04-17 01:01:26 | ERROR | stderr |   File "D:\Program_files\anaconda\envs\chatchat1\lib\site-packages\torch\nn\modules\module.py", line 810, in _apply
2024-04-17 01:01:26 | ERROR | stderr |     module._apply(fn)
2024-04-17 01:01:26 | ERROR | stderr |   File "D:\Program_files\anaconda\envs\chatchat1\lib\site-packages\torch\nn\modules\module.py", line 810, in _apply
2024-04-17 01:01:26 | ERROR | stderr |     module._apply(fn)
2024-04-17 01:01:26 | ERROR | stderr |   File "D:\Program_files\anaconda\envs\chatchat1\lib\site-packages\torch\nn\modules\module.py", line 833, in _apply
2024-04-17 01:01:26 | ERROR | stderr |     param_applied = fn(param)
2024-04-17 01:01:26 | ERROR | stderr |   File "D:\Program_files\anaconda\envs\chatchat1\lib\site-packages\torch\nn\modules\module.py", line 1158, in convert
2024-04-17 01:01:26 | ERROR | stderr |     return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
2024-04-17 01:01:26 | ERROR | stderr |   File "D:\Program_files\anaconda\envs\chatchat1\lib\site-packages\torch\cuda\__init__.py", line 289, in _lazy_init
2024-04-17 01:01:26 | ERROR | stderr |     raise AssertionError("Torch not compiled with CUDA enabled")
2024-04-17 01:01:26 | ERROR | stderr | AssertionError: Torch not compiled with CUDA enabled
